inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'railties/test/fixtures/tmp/**/*'
    - 'node_modules/**/*'
  Rails:
    Enabled: true

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyleForEmptyBraces: space

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Metrics/LineLength:
  Enabled: false
